/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Kévin
 */
public class ChatView extends javax.swing.JFrame {
    
    private final ChatModel model;

    /**
     * Creates new form Interface
     * @param _model ChatView Model
     */
    public ChatView(ChatModel _model) {
        model = _model;
        initComponents();
        chat_screen.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chat_window = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat_screen = new javax.swing.JTextArea();
        message_field = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("chat");
        setBackground(new java.awt.Color(32, 164, 228));

        chat_window.setBackground(new java.awt.Color(32, 164, 228));

        chat_screen.setEditable(false);
        chat_screen.setColumns(20);
        chat_screen.setRows(5);
        jScrollPane1.setViewportView(chat_screen);
        chat_screen.getAccessibleContext().setAccessibleName("");

        message_field.setEditable(false);
        message_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        message_field.setToolTipText("");
        message_field.setMaximumSize(new java.awt.Dimension(200, 40));

        btn_send.setBackground(new java.awt.Color(255, 255, 255));
        btn_send.setForeground(new java.awt.Color(32, 164, 228));
        btn_send.setText("Send");
        btn_send.setEnabled(false);

        javax.swing.GroupLayout chat_windowLayout = new javax.swing.GroupLayout(chat_window);
        chat_window.setLayout(chat_windowLayout);
        chat_windowLayout.setHorizontalGroup(
            chat_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chat_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGroup(chat_windowLayout.createSequentialGroup()
                        .addComponent(message_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_send)))
                .addContainerGap())
        );
        chat_windowLayout.setVerticalGroup(
            chat_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(chat_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(message_field, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chat_window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chat_window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * Update method
     */
    public void update()
    {
        message_field.setText("");
        afficheMessage(model.getMessage(model.sizeMessage()));
    }
    
    /**
     * Add message in ChatView Area
     */
    private void afficheMessage(Message _message)
    {
        chat_screen.append(_message.toString());
    }
    
    
    
    /**
     * Getter send button
     * @return JButton
     */
    public JButton getBtnSend()
    {
        return btn_send;
    }
    
    /**
     * Setter send button
     * @param _button
     */
    public void setBtnSend(JButton _button)
    {
        btn_send = _button;
    }
    
    /**
     * Getter chat text area
     * @return JTextArea
     */
    public JTextArea getChatScreen()
    {
        return chat_screen;
    }
    
    /**
     * Setter chat text area
     * @param _textArea
     */
    public void setChatScreen(JTextArea _textArea)
    {
        chat_screen = _textArea;
    }
    
    /**
     * Getter message field
     * @return JTextField
     */
    public JTextField getMessageField()
    {
        return message_field;
    }
    
    /**
     * Setter message field
     * @param _messageField
     */
    public void setMessageField(JTextField _messageField)
    {
        message_field = _messageField;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JTextArea chat_screen;
    private javax.swing.JPanel chat_window;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message_field;
    // End of variables declaration//GEN-END:variables
}
