/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z_clientlourd;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author VOCAN
 */
public class ChatView extends javax.swing.JPanel {
    
    private final ChatModel model;

    /**
     * Creates new form ChatView
     * @param _model
     */
    public ChatView(ChatModel _model) {
        model = _model;
        initComponents();
        chat_screen.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chat_screen = new javax.swing.JTextArea();
        message_field = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 600));
        setPreferredSize(new java.awt.Dimension(200, 600));

        chat_screen.setEditable(false);
        chat_screen.setColumns(20);
        chat_screen.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        chat_screen.setRows(5);
        jScrollPane1.setViewportView(chat_screen);

        message_field.setEditable(false);
        message_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        message_field.setMinimumSize(new java.awt.Dimension(100, 50));
        message_field.setPreferredSize(new java.awt.Dimension(100, 50));

        btn_send.setText("Send");
        btn_send.setEnabled(false);
        btn_send.setMaximumSize(new java.awt.Dimension(75, 50));
        btn_send.setMinimumSize(new java.awt.Dimension(75, 50));
        btn_send.setPreferredSize(new java.awt.Dimension(75, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JTextArea chat_screen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message_field;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Update method
     */
    public void update()
    {
        message_field.setText("");
        afficheMessage(model.getMessage(model.sizeMessage()));
    }
    
    /**
     * Add message in ChatView Area
     */
    private void afficheMessage(Message _message)
    {
        chat_screen.append(_message.toString());
    }
    
    /**
     * Getter send button
     * @return JButton
     */
    public JButton getBtnSend()
    {
        return btn_send;
    }
    
    /**
     * Setter send button
     * @param _button
     */
    public void setBtnSend(JButton _button)
    {
        btn_send = _button;
    }
    
    /**
     * Getter chat text area
     * @return JTextArea
     */
    public JTextArea getChatScreen()
    {
        return chat_screen;
    }
    
    /**
     * Setter chat text area
     * @param _textArea
     */
    public void setChatScreen(JTextArea _textArea)
    {
        chat_screen = _textArea;
    }
    
    /**
     * Getter message field
     * @return JTextField
     */
    public JTextField getMessageField()
    {
        return message_field;
    }
    
    /**
     * Setter message field
     * @param _messageField
     */
    public void setMessageField(JTextField _messageField)
    {
        message_field = _messageField;
    }
}
