/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z_clientlourd;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author VOCAN
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    private DefaultTreeModel model;
    private static ChatModel m;
    private static ChatController c;
    
    
    public HomeFrame() throws IOException {
        m = new ChatModel();
        
        initComponents();
        initTree();
        
        System.out.println("aaaaa");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPrincipal = new javax.swing.JSplitPane();
        SplitEditor = new javax.swing.JSplitPane();
        Chat = new ChatView(m);
        Editor = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane4 = new javax.swing.JEditorPane();
        SplitTree = new javax.swing.JScrollPane();
        Tree = new javax.swing.JTree();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newProject = new javax.swing.JMenuItem();
        newFile = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        SplitEditor.setLeftComponent(Chat);

        Editor.setBackground(new java.awt.Color(255, 255, 255));
        Editor.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Editor.setOpaque(true);

        jScrollPane1.setViewportView(jEditorPane1);

        Editor.addTab("tab1", jScrollPane1);

        jScrollPane3.setViewportView(jEditorPane2);

        Editor.addTab("tab2", jScrollPane3);

        jScrollPane4.setViewportView(jEditorPane3);

        Editor.addTab("tab3", jScrollPane4);

        jScrollPane5.setViewportView(jEditorPane4);

        Editor.addTab("tab4", jScrollPane5);

        SplitEditor.setRightComponent(Editor);

        SplitPrincipal.setRightComponent(SplitEditor);

        SplitTree.setViewportView(Tree);

        SplitPrincipal.setLeftComponent(SplitTree);

        getContentPane().add(SplitPrincipal, java.awt.BorderLayout.CENTER);

        Menu.setMinimumSize(new java.awt.Dimension(800, 50));
        Menu.setPreferredSize(new java.awt.Dimension(800, 50));

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        newProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        newProject.setText("New project");
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });
        file.add(newProject);

        newFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFile.setText("New file");
        newFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileActionPerformed(evt);
            }
        });
        file.add(newFile);

        Menu.add(file);

        view.setText("View");
        view.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu.add(view);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTree() throws IOException
    {
        Chat.add(new ChatView(m));
        Chat.repaint();
        Chat.revalidate();
        Chat.setVisible(true);
        model = (DefaultTreeModel) Tree.getModel();
    }
    
    private void newFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileActionPerformed
        // TODO add your handling code here:
        String filename;
        DefaultMutableTreeNode selectedNode;
        
        selectedNode = (DefaultMutableTreeNode) Tree.getSelectionPath().getLastPathComponent();
        if(selectedNode != null)
        {
            filename = JOptionPane.showInputDialog("File Name :");
            selectedNode.insert(new DefaultMutableTreeNode(filename),selectedNode.getIndex(selectedNode.getLastChild()));
            model.reload(selectedNode);
        }
    }//GEN-LAST:event_newFileActionPerformed

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "New Project");
    }//GEN-LAST:event_newProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomeFrame().setVisible(true);
                    
                    Thread t = new Thread(new ChatController(m, (ChatView) Chat));
                    t.start();
                } catch (IOException ex) {
                    Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel Chat;
    private javax.swing.JTabbedPane Editor;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JSplitPane SplitEditor;
    private javax.swing.JSplitPane SplitPrincipal;
    private javax.swing.JScrollPane SplitTree;
    private javax.swing.JTree Tree;
    private javax.swing.JMenu file;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JEditorPane jEditorPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenuItem newFile;
    private javax.swing.JMenuItem newProject;
    private javax.swing.JMenu view;
    // End of variables declaration//GEN-END:variables
}
